### ISSUE TITLE
Bug In Service Quantity Update 

### ISSUE THREAD

**Issue by micihn** [micihn/PORTOKO#45]
## Module
fleet_service

## Describe the bug

- [x] Update kuantitas dari operasi Permintaan Barang tidak berkerja kalau ada 2 barang dalam 1 service

![image](https://github.com/micihn/PORTOKO/assets/108042879/5d735fca-cc1f-41da-9d7c-2acf4f6e9d7a)
![image](https://github.com/micihn/PORTOKO/assets/108042879/1c907c9d-819d-4b22-b008-0c5a32460ff3)
Barang tidak terupdate, dan log keliru menuli barang yang kuantitasnya di update
![image](https://github.com/micihn/PORTOKO/assets/108042879/3374a670-e96c-455d-8a6a-80fb1965dead)
Saat diretur barang yang kuantitasnya boleh diretur juga terbalik

- [x] Operasi Keluar Barang menggabung semua permintaan barang. Baiknya tiap service/tiap permintaan tetap 1 record operasi
![image](https://github.com/micihn/PORTOKO/assets/108042879/23017baa-df6f-4fc5-85f1-6351a5326bbc)
1 Operasi Keluar Barang ternyata gabungan dari beberapa operasi permintaan dan service

**Comment by altela** [comment]
noted, working on this

**Comment by micihn** [comment]
Untuk Simplified Process dan Mengatasi Picking Merged di Operasi Keluar Barang
Plan:
Operasi Permintaan Barang di Inventory akan dihilangkan dan permintaan akan dipindah ke Service
Prefix berubah dari SE jadi PB
Kalau kategori yang dipilih adalah Expense Lain-lain (selain spareparts) maka prefix tetap SE apakah bisa?
Buat service -> validate -> keluar barang -> validate keluar barang

**Comment by altela** [comment]
ok done, untuk detail workflow saya taro di video yah
